# Create the 1st  named layer\intermediate image
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
# create or go into folder /app
WORKDIR /app
# Expose port 80
EXPOSE 80
COPY  app/. .
ENTRYPOINT ["dotnet", "dockerapp.dll"]
